### ISSUE TITLE
Exception with jQueryMobile 1.3.0

### ISSUE THREAD

**Issue by ronlussier** [ToddThomson/jQuery-Mobile-Subpage-Widget#20]
With the advent of jQueryMobile 1.3.0, I am getting an exception on line 98 of the plugin.  This code:

```
        if ( this.parentPage.is(":jqmData(external-page='true')") &&
             this.parentPage.data("page").options.domCache === false) {
```

causes an exception on some page transitions, because 'this.parentPage.data("page")' is undefined.  I've added a check in my version of the plugin for this, but I'm curious as to whether this is part of a larger problem that I'm not seeing?

**Comment by ToddThomson** [comment]
Hi Ron, it looks like jQM version 1.3 now uses:

this.parentPage.data("mobile-page") rather than this.parentPage.data("page")

So, given a _very_ cursory look, it appears that for jQM 1.3, the subpage widget will need to be changed accordingly.

Can you make this change, test it and issue a pull request? I won't be able to do get to this until next month.

Thanks, Todd

**Comment by ronlussier** [comment]
Will do.

**Comment by ronlussier** [comment]
[Pull request submitted](https://github.com/ToddThomson/jQuery-Mobile-Subpage-Widget/pull/21).
