### ISSUE TITLE
Refresh doesn't take you back to subpage

### ISSUE THREAD

**Issue by joshmouch** [ToddThomson/jQuery-Mobile-Subpage-Widget#22]
On your demo site, if you go to http://m.integra-international.net/home/about and then click about, you are redirected to http://m.integra-international.net/home/about#&ui-page=mid-mobile-about.

However, if you now hit refresh, the URL stays the same, but the actual page displayed is http://m.integra-international.net/home/about.

**Comment by ToddThomson** [comment]
Hi Josh, I'm too busy at the moment to work through this issue. Would you construct a simple test applet to reproduce the issue? Please submit a pull request if you are able to modify the subpage widget to remedy the issue.
Without looking at all, I suspect that the issue is in the jQM navigation system.

**Comment by joshmouch** [comment]
I've submitted a bug report to jQM on a similar issue with their dialog box demo.  Hopefully this fixes this subpage issue, as well.
